package com.myoprj.myochecker;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SensorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sensor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float arg0 = 1;</code>
     */
    float getArg0();

    /**
     * <code>optional float arg1 = 2;</code>
     */
    float getArg1();

    /**
     * <code>optional float arg2 = 3;</code>
     */
    float getArg2();

    /**
     * <code>optional float arg3 = 4;</code>
     */
    float getArg3();

    /**
     * <code>optional float arg4 = 5;</code>
     */
    float getArg4();

    /**
     * <code>optional float arg5 = 6;</code>
     */
    float getArg5();

    /**
     * <code>optional float arg6 = 7;</code>
     */
    float getArg6();

    /**
     * <code>optional float arg7 = 8;</code>
     */
    float getArg7();
  }
  /**
   * Protobuf type {@code Sensor}
   */
  public  static final class Sensor extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Sensor)
      SensorOrBuilder {
    // Use Sensor.newBuilder() to construct.
    private Sensor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Sensor() {
      arg0_ = 0F;
      arg1_ = 0F;
      arg2_ = 0F;
      arg3_ = 0F;
      arg4_ = 0F;
      arg5_ = 0F;
      arg6_ = 0F;
      arg7_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Sensor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              arg0_ = input.readFloat();
              break;
            }
            case 21: {

              arg1_ = input.readFloat();
              break;
            }
            case 29: {

              arg2_ = input.readFloat();
              break;
            }
            case 37: {

              arg3_ = input.readFloat();
              break;
            }
            case 45: {

              arg4_ = input.readFloat();
              break;
            }
            case 53: {

              arg5_ = input.readFloat();
              break;
            }
            case 61: {

              arg6_ = input.readFloat();
              break;
            }
            case 69: {

              arg7_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Data.internal_static_Sensor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Data.internal_static_Sensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.Sensor.class, Data.Sensor.Builder.class);
    }

    public static final int ARG0_FIELD_NUMBER = 1;
    private float arg0_;
    /**
     * <code>optional float arg0 = 1;</code>
     */
    public float getArg0() {
      return arg0_;
    }

    public static final int ARG1_FIELD_NUMBER = 2;
    private float arg1_;
    /**
     * <code>optional float arg1 = 2;</code>
     */
    public float getArg1() {
      return arg1_;
    }

    public static final int ARG2_FIELD_NUMBER = 3;
    private float arg2_;
    /**
     * <code>optional float arg2 = 3;</code>
     */
    public float getArg2() {
      return arg2_;
    }

    public static final int ARG3_FIELD_NUMBER = 4;
    private float arg3_;
    /**
     * <code>optional float arg3 = 4;</code>
     */
    public float getArg3() {
      return arg3_;
    }

    public static final int ARG4_FIELD_NUMBER = 5;
    private float arg4_;
    /**
     * <code>optional float arg4 = 5;</code>
     */
    public float getArg4() {
      return arg4_;
    }

    public static final int ARG5_FIELD_NUMBER = 6;
    private float arg5_;
    /**
     * <code>optional float arg5 = 6;</code>
     */
    public float getArg5() {
      return arg5_;
    }

    public static final int ARG6_FIELD_NUMBER = 7;
    private float arg6_;
    /**
     * <code>optional float arg6 = 7;</code>
     */
    public float getArg6() {
      return arg6_;
    }

    public static final int ARG7_FIELD_NUMBER = 8;
    private float arg7_;
    /**
     * <code>optional float arg7 = 8;</code>
     */
    public float getArg7() {
      return arg7_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (arg0_ != 0F) {
        output.writeFloat(1, arg0_);
      }
      if (arg1_ != 0F) {
        output.writeFloat(2, arg1_);
      }
      if (arg2_ != 0F) {
        output.writeFloat(3, arg2_);
      }
      if (arg3_ != 0F) {
        output.writeFloat(4, arg3_);
      }
      if (arg4_ != 0F) {
        output.writeFloat(5, arg4_);
      }
      if (arg5_ != 0F) {
        output.writeFloat(6, arg5_);
      }
      if (arg6_ != 0F) {
        output.writeFloat(7, arg6_);
      }
      if (arg7_ != 0F) {
        output.writeFloat(8, arg7_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (arg0_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, arg0_);
      }
      if (arg1_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, arg1_);
      }
      if (arg2_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, arg2_);
      }
      if (arg3_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, arg3_);
      }
      if (arg4_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, arg4_);
      }
      if (arg5_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, arg5_);
      }
      if (arg6_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, arg6_);
      }
      if (arg7_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, arg7_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Data.Sensor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data.Sensor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data.Sensor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data.Sensor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data.Sensor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data.Sensor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Data.Sensor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Data.Sensor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Data.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Data.Sensor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sensor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sensor)
        Data.SensorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Data.internal_static_Sensor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Data.internal_static_Sensor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.Sensor.class, Data.Sensor.Builder.class);
      }

      // Construct using Data.Sensor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        arg0_ = 0F;

        arg1_ = 0F;

        arg2_ = 0F;

        arg3_ = 0F;

        arg4_ = 0F;

        arg5_ = 0F;

        arg6_ = 0F;

        arg7_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Data.internal_static_Sensor_descriptor;
      }

      public Data.Sensor getDefaultInstanceForType() {
        return Data.Sensor.getDefaultInstance();
      }

      public Data.Sensor build() {
        Data.Sensor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Data.Sensor buildPartial() {
        Data.Sensor result = new Data.Sensor(this);
        result.arg0_ = arg0_;
        result.arg1_ = arg1_;
        result.arg2_ = arg2_;
        result.arg3_ = arg3_;
        result.arg4_ = arg4_;
        result.arg5_ = arg5_;
        result.arg6_ = arg6_;
        result.arg7_ = arg7_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data.Sensor) {
          return mergeFrom((Data.Sensor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data.Sensor other) {
        if (other == Data.Sensor.getDefaultInstance()) return this;
        if (other.getArg0() != 0F) {
          setArg0(other.getArg0());
        }
        if (other.getArg1() != 0F) {
          setArg1(other.getArg1());
        }
        if (other.getArg2() != 0F) {
          setArg2(other.getArg2());
        }
        if (other.getArg3() != 0F) {
          setArg3(other.getArg3());
        }
        if (other.getArg4() != 0F) {
          setArg4(other.getArg4());
        }
        if (other.getArg5() != 0F) {
          setArg5(other.getArg5());
        }
        if (other.getArg6() != 0F) {
          setArg6(other.getArg6());
        }
        if (other.getArg7() != 0F) {
          setArg7(other.getArg7());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Data.Sensor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Data.Sensor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float arg0_ ;
      /**
       * <code>optional float arg0 = 1;</code>
       */
      public float getArg0() {
        return arg0_;
      }
      /**
       * <code>optional float arg0 = 1;</code>
       */
      public Builder setArg0(float value) {
        
        arg0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg0 = 1;</code>
       */
      public Builder clearArg0() {
        
        arg0_ = 0F;
        onChanged();
        return this;
      }

      private float arg1_ ;
      /**
       * <code>optional float arg1 = 2;</code>
       */
      public float getArg1() {
        return arg1_;
      }
      /**
       * <code>optional float arg1 = 2;</code>
       */
      public Builder setArg1(float value) {
        
        arg1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg1 = 2;</code>
       */
      public Builder clearArg1() {
        
        arg1_ = 0F;
        onChanged();
        return this;
      }

      private float arg2_ ;
      /**
       * <code>optional float arg2 = 3;</code>
       */
      public float getArg2() {
        return arg2_;
      }
      /**
       * <code>optional float arg2 = 3;</code>
       */
      public Builder setArg2(float value) {
        
        arg2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg2 = 3;</code>
       */
      public Builder clearArg2() {
        
        arg2_ = 0F;
        onChanged();
        return this;
      }

      private float arg3_ ;
      /**
       * <code>optional float arg3 = 4;</code>
       */
      public float getArg3() {
        return arg3_;
      }
      /**
       * <code>optional float arg3 = 4;</code>
       */
      public Builder setArg3(float value) {
        
        arg3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg3 = 4;</code>
       */
      public Builder clearArg3() {
        
        arg3_ = 0F;
        onChanged();
        return this;
      }

      private float arg4_ ;
      /**
       * <code>optional float arg4 = 5;</code>
       */
      public float getArg4() {
        return arg4_;
      }
      /**
       * <code>optional float arg4 = 5;</code>
       */
      public Builder setArg4(float value) {
        
        arg4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg4 = 5;</code>
       */
      public Builder clearArg4() {
        
        arg4_ = 0F;
        onChanged();
        return this;
      }

      private float arg5_ ;
      /**
       * <code>optional float arg5 = 6;</code>
       */
      public float getArg5() {
        return arg5_;
      }
      /**
       * <code>optional float arg5 = 6;</code>
       */
      public Builder setArg5(float value) {
        
        arg5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg5 = 6;</code>
       */
      public Builder clearArg5() {
        
        arg5_ = 0F;
        onChanged();
        return this;
      }

      private float arg6_ ;
      /**
       * <code>optional float arg6 = 7;</code>
       */
      public float getArg6() {
        return arg6_;
      }
      /**
       * <code>optional float arg6 = 7;</code>
       */
      public Builder setArg6(float value) {
        
        arg6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg6 = 7;</code>
       */
      public Builder clearArg6() {
        
        arg6_ = 0F;
        onChanged();
        return this;
      }

      private float arg7_ ;
      /**
       * <code>optional float arg7 = 8;</code>
       */
      public float getArg7() {
        return arg7_;
      }
      /**
       * <code>optional float arg7 = 8;</code>
       */
      public Builder setArg7(float value) {
        
        arg7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float arg7 = 8;</code>
       */
      public Builder clearArg7() {
        
        arg7_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Sensor)
    }

    // @@protoc_insertion_point(class_scope:Sensor)
    private static final Data.Sensor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Data.Sensor();
    }

    public static Data.Sensor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sensor>
        PARSER = new com.google.protobuf.AbstractParser<Sensor>() {
      public Sensor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Sensor(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Sensor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sensor> getParserForType() {
      return PARSER;
    }

    public Data.Sensor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Sensor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sensor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\"x\n\006Sensor\022\014\n\004arg0\030\001 \001(\002\022\014\n\004" +
      "arg1\030\002 \001(\002\022\014\n\004arg2\030\003 \001(\002\022\014\n\004arg3\030\004 \001(\002\022\014" +
      "\n\004arg4\030\005 \001(\002\022\014\n\004arg5\030\006 \001(\002\022\014\n\004arg6\030\007 \001(\002" +
      "\022\014\n\004arg7\030\010 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Sensor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Sensor_descriptor,
        new java.lang.String[] { "Arg0", "Arg1", "Arg2", "Arg3", "Arg4", "Arg5", "Arg6", "Arg7", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
